import jsPDF from 'jspdf';
import confetti from 'canvas-confetti';
import { MovieProject } from '../types';

export function triggerConfetti() {
  confetti({
    particleCount: 80,
    spread: 70,
    origin: { y: 0.6 },
    colors: ['#3B82F6', '#8B5CF6', '#EC4899', '#06B6D4', '#10B981'],
  });
}

export function downloadJSON(project: MovieProject) {
  const dataStr = 'data:text/json;charset=utf-8,' + encodeURIComponent(JSON.stringify(project, null, 2));
  const downloadAnchor = document.createElement('a');
  downloadAnchor.setAttribute('href', dataStr);
  downloadAnchor.setAttribute('download', `${project.title.toLowerCase().replace(/[^a-z0-9]/g, '_')}_cinema_package.json`);
  document.body.appendChild(downloadAnchor);
  downloadAnchor.click();
  downloadAnchor.remove();
  triggerConfetti();
}

export function generateMarkdown(project: MovieProject): string {
  return `# 🎬 PROMPT CINEMA AI — PRODUCTION PACKAGE
## Title: ${project.title}
**Genre:** ${project.genre}  
**Tagline:** *"${project.tagline}"*  
**Logline:** ${project.logline}  
**Hook:** ${project.hook}  

---

### 1. STORY & SYNOPSIS
${project.synopsis}

#### Three-Act Structure
- **Act I:** ${project.threeActStructure.act1}
- **Act II:** ${project.threeActStructure.act2}
- **Act III:** ${project.threeActStructure.act3}

#### Characters
${project.characters
  .map(
    (c) => `* **${c.name}** (${c.role} / ${c.archetype}): ${c.personality}\n  *Backstory:* ${c.backstory}\n  *Motivation:* ${c.motivation}`
  )
  .join('\n\n')}

**Plot Twist:** ${project.plotTwist}  
**Ending:** ${project.ending}  
**Themes:** ${project.themes.join(', ')}

---

### 2. SCREENPLAY
${project.screenplay
  .map(
    (s) => `#### SCENE ${s.sceneNumber}: ${s.heading}
${s.action}

${s.dialogueLines
  .map((d) => `${d.character.toUpperCase()}\n${d.parenthetical ? d.parenthetical + '\n' : ''}"${d.line}"`)
  .join('\n\n')}

*${s.transition || 'CUT TO:'}*`
  )
  .join('\n\n---\n\n')}

---

### 3. SHOT LIST
| Scene | Shot | Type | Lens | Movement | Purpose | Duration |
|-------|------|------|------|----------|---------|----------|
${project.shotList
  .map((s) => `| ${s.sceneNumber} | ${s.shotNumber} | ${s.shotType} | ${s.lens} | ${s.movement} | ${s.purpose} | ${s.duration} |`)
  .join('\n')}

---

### 4. CINEMATOGRAPHY
- **Camera Angles:** ${project.cinematography.cameraAngle}
- **Lenses:** ${project.cinematography.cameraLens}
- **Depth of Field:** ${project.cinematography.depthOfField}
- **Movement Style:** ${project.cinematography.movementStyle}
- **Lighting Setup:**
  - Key: ${project.cinematography.lighting.key}
  - Fill: ${project.cinematography.lighting.fill}
  - Backlight: ${project.cinematography.lighting.backlight}
  - Practicals: ${project.cinematography.lighting.practicals}
- **Color Temperature:** ${project.cinematography.colorTemperature}
- **Composition:** ${project.cinematography.compositionRules}
- **Visual Mood:** ${project.cinematography.mood}

---

### 5. STORYBOARD PROMPTS
${project.storyboardPrompts
  .map(
    (sb) => `#### Scene ${sb.sceneNumber} - Frame ${sb.frameNumber}: ${sb.title}
- **Prompt:** ${sb.imagePrompt}
- **Negative Prompt:** ${sb.negativePrompt}
- **Style:** ${sb.style} | **Camera:** ${sb.camera} | **Lighting:** ${sb.lighting}`
  )
  .join('\n\n')}

---

### 6. VIDEO PROMPTS (Google Veo / Runway / Sora / Luma)
${project.videoPrompts
  .map(
    (v) => `#### Platform: ${v.targetPlatform}
- **Prompt:** ${v.subject}, ${v.action}, ${v.cameraMovement}, ${v.lighting}, ${v.style}, ${v.aspectRatio}, ${v.duration}`
  )
  .join('\n\n')}

---

### 7. MUSIC & AUDIO
- **Music Genre:** ${project.music.genre}
- **Tempo:** ${project.music.tempo} | **Key:** ${project.music.key}
- **Instrumentation:** ${project.music.instrumentation.join(', ')}
- **Music Prompt:** ${project.music.musicPrompt}
- **Narration:** "${project.voiceover.narration}"

---

### 8. PRODUCTION PLAN
- **Crew:** ${project.productionPlan.crew.join(', ')}
- **Equipment:** ${project.productionPlan.equipment.join(', ')}
- **Budget Estimate:** ${project.productionPlan.budgetEstimate}
- **Schedule:** ${project.productionPlan.schedule}
- **Risk Analysis:** ${project.productionPlan.riskAnalysis}

---

*Generated by Prompt Cinema AI — Professional AI Filmmaking Platform*
`;
}

export function downloadMarkdown(project: MovieProject) {
  const markdownText = generateMarkdown(project);
  const dataStr = 'data:text/markdown;charset=utf-8,' + encodeURIComponent(markdownText);
  const downloadAnchor = document.createElement('a');
  downloadAnchor.setAttribute('href', dataStr);
  downloadAnchor.setAttribute('download', `${project.title.toLowerCase().replace(/[^a-z0-9]/g, '_')}_production_book.md`);
  document.body.appendChild(downloadAnchor);
  downloadAnchor.click();
  downloadAnchor.remove();
  triggerConfetti();
}

export function downloadDocxText(project: MovieProject) {
  const markdownText = generateMarkdown(project);
  const dataStr = 'data:text/plain;charset=utf-8,' + encodeURIComponent(markdownText);
  const downloadAnchor = document.createElement('a');
  downloadAnchor.setAttribute('href', dataStr);
  downloadAnchor.setAttribute('download', `${project.title.toLowerCase().replace(/[^a-z0-9]/g, '_')}_screenplay_doc.docx`);
  document.body.appendChild(downloadAnchor);
  downloadAnchor.click();
  downloadAnchor.remove();
  triggerConfetti();
}

export function downloadPDF(project: MovieProject) {
  const doc = new jsPDF({
    unit: 'pt',
    format: 'a4',
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  let y = 50;

  // Header
  doc.setFillColor(11, 15, 25);
  doc.rect(0, 0, pageWidth, 80, 'F');

  doc.setTextColor(59, 130, 246);
  doc.setFontSize(22);
  doc.text('PROMPT CINEMA AI', 40, 42);

  doc.setTextColor(200, 200, 220);
  doc.setFontSize(10);
  doc.text('HOLLYWOOD-GRADE PRE-PRODUCTION PACKAGE', 40, 60);

  y = 110;

  // Title & Logline
  doc.setTextColor(30, 30, 40);
  doc.setFontSize(18);
  doc.text(project.title.toUpperCase(), 40, y);
  y += 20;

  doc.setFontSize(11);
  doc.setTextColor(80, 80, 100);
  doc.text(`Genre: ${project.genre}`, 40, y);
  y += 18;

  doc.setFontSize(10);
  doc.setTextColor(50, 50, 60);
  const splitLogline = doc.splitTextToSize(`Logline: ${project.logline}`, pageWidth - 80);
  doc.text(splitLogline, 40, y);
  y += splitLogline.length * 14 + 20;

  // Synopsis
  doc.setFontSize(12);
  doc.setTextColor(139, 92, 246);
  doc.text('1. STORY SYNOPSIS', 40, y);
  y += 16;

  doc.setFontSize(9);
  doc.setTextColor(40, 40, 50);
  const splitSynopsis = doc.splitTextToSize(project.synopsis, pageWidth - 80);
  doc.text(splitSynopsis, 40, y);
  y += splitSynopsis.length * 12 + 25;

  // Check Page break
  if (y > 700) {
    doc.addPage();
    y = 50;
  }

  // Screenplay preview
  doc.setFontSize(12);
  doc.setTextColor(139, 92, 246);
  doc.text('2. SCREENPLAY SCENES', 40, y);
  y += 18;

  project.screenplay.slice(0, 3).forEach((scene) => {
    if (y > 720) {
      doc.addPage();
      y = 50;
    }
    doc.setFontSize(10);
    doc.setTextColor(20, 20, 25);
    doc.text(`SCENE ${scene.sceneNumber}: ${scene.heading}`, 40, y);
    y += 14;

    doc.setFontSize(9);
    doc.setTextColor(60, 60, 70);
    const splitAction = doc.splitTextToSize(scene.action, pageWidth - 80);
    doc.text(splitAction, 40, y);
    y += splitAction.length * 12 + 10;

    scene.dialogueLines.forEach((d) => {
      if (y > 740) {
        doc.addPage();
        y = 50;
      }
      doc.setFontSize(9);
      doc.setTextColor(10, 10, 10);
      doc.text(d.character.toUpperCase(), pageWidth / 2, y, { align: 'center' });
      y += 12;
      if (d.parenthetical) {
        doc.text(d.parenthetical, pageWidth / 2, y, { align: 'center' });
        y += 12;
      }
      const splitLine = doc.splitTextToSize(`"${d.line}"`, pageWidth - 200);
      doc.text(splitLine, pageWidth / 2, y, { align: 'center' });
      y += splitLine.length * 12 + 12;
    });

    y += 10;
  });

  // Footer on all pages
  const totalPages = (doc as any).internal.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 160);
    doc.text(`Prompt Cinema AI — Page ${i} of ${totalPages}`, pageWidth - 160, 820);
  }

  doc.save(`${project.title.toLowerCase().replace(/[^a-z0-9]/g, '_')}_filmmaking_package.pdf`);
  triggerConfetti();
}

export function downloadRenderConfig(project: MovieProject) {
  const yamlContent = `services:
  - type: web
    name: ${project.title.toLowerCase().replace(/[^a-z0-9]/g, '-')}-cinema
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NPM_CONFIG_PRODUCTION
        value: "false"
      - key: GEMINI_API_KEY
        sync: false
`;

  const blob = new Blob([yamlContent], { type: 'text/yaml' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `render.yaml`;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
  triggerConfetti();
}

export function copyToClipboard(text: string): Promise<void> {
  return navigator.clipboard.writeText(text);
}
